[project]
name = "a2a-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bedrock-agentcore>=1.1.1",
    "strands-agents-tools>=0.2.18",
    "strands-agents[a2a]>=1.20.0",
]
